name: dartling_gen
version: 0.1.0
author: Dzenan Ridjanovic <dzenanr@gmail.com>
description: Generate a new dartling project.
homepage: http://ondart.me/
dependencies:
  browser: any
  dartling:
    git: git://github.com/dzenanr/dartling.git
