name: dartling_gen
version: 1.0.3
author: Dzenan Ridjanovic <dzenanr@gmail.com>
description: Generate a new dartling project.
homepage: https://github.com/dzenanr/dartling_gen
environment:
  sdk: '>=0.8.10+8 <2.0.0'
documentation: http://goo.gl/Fd08zZ
dependencies:
  browser: '>=0.9.0 <0.10.0'
  dartling: '>=1.0.6 <2.0.0'
