name: dartling_gen
version: 2.0.1
description: Generate a new dartling project.
author: Dzenan Ridjanovic <dzenanr@gmail.com>
homepage: https://github.com/dzenanr/dartling_gen
documentation: http://goo.gl/Fd08zZ
dependencies:
  dartling:
    git: 'https://github.com/dzenanr/dartling.git'

