name: dartling_gen
version: 2.0.2
description: Generate a new dartling project.
author: Dzenan Ridjanovic <dzenanr@gmail.com>
homepage: https://github.com/dzenanr/dartling_gen
documentation: http://goo.gl/Fd08zZ
environment:
  sdk: '>=1.10.0 <2.0.0'
dependencies:
  dartling: ^2.0.2

